WebApplication4/Models/Oto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class Oto
    {
        [Key]
        public int AracId { get; set; }

        [Display(Name = "Arac Marka")]
        [Required(ErrorMessage = "Arac Marka Giriniz", AllowEmptyStrings = false)] //Required Islemi yaptiriyoruz
        public string Marka { get; set; }
        [Display(Name = "Arac Model")]
        [Required(ErrorMessage = "Arac Model Giriniz", AllowEmptyStrings = false)]
        public string Model { get; set; }


    }
}

WebApplication4/Models/ViewModel/OtoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication4.Models.ViewModel
{
    public class OtoViewModel
    {
        

       
        
            public Oto Ato { get; set; }
            public IEnumerable<Oto> Otomobil { get; set; }
        }
    }

WebApplication4/Controllers/OtoController.cs
using KaraerAuto.Dal;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using WebApplication4.Models.ViewModel;

namespace WebApplication4.Controllers
{
    public class OtoController : Controller
    {
        //GET: Oto
        OtoContext ctx = new OtoContext();
        [Authorize]
        public ActionResult Index()
        {

            using (OtoContext ctx = new OtoContext())
            {
                OtoViewModel ovm = new OtoViewModel
                {
                    Otomobil = ctx.Otomobil.ToList()
                };

                return View(ovm);
            }

        }

        [Authorize]
        public ActionResult Ekle()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        public bool Ekle(Oto o)
        {

            if (ModelState.IsValid)
            {
                using (OtoContext ctx = new OtoContext())
                {
                    ctx.Otomobil.Add(o);
                    int sonuc = ctx.SaveChanges();
                    if (sonuc > 0)
                    {
                        return true;
                    }

                }
            }
            else
            {
                ModelState.AddModelError("AracId", "Bos");
            }
            return false;
        }

        public string Listele()
        {
            string liste = "";
            List<Oto> otolistesi = ctx.Otomobil.ToList();
            foreach (var list in otolistesi)
            {
                liste += "<br>" + list.Marka + " " + list.Model + "<hr>";
            }
            return liste;
        }
        [Authorize]
        public ActionResult Duzenle(int? id)
        {
            using (OtoContext ctx = new OtoContext())
            {
                var ato = ctx.Otomobil.Find(id);

                return View(ato);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Duzenle(Oto ato)
        {
            using (OtoContext ctx = new OtoContext())
            {
                ctx.Entry(ato).State = EntityState.Modified;
                int sonuc = ctx.SaveChanges();
                if (sonuc > 0)
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        [Authorize]
        public ActionResult Sil(int? id)
        {
            using (OtoContext ctx = new OtoContext())
            {
                var ato = ctx.Otomobil.Find(id);
                ctx.Otomobil.Remove(ato);
                ctx.SaveChanges();
                return RedirectToAction("Index");

            }
        }
    }
}

WebApplication4/Views/Oto/Duzenle.cshtml
@model WebApplication4.Models.Oto


@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/_DuzenleAdmin.cshtml";
}

<h2>Arac Bilgileri Düzenleme İşlemi</h2>

@using (Html.BeginForm("Duzenle", "Oto", FormMethod.Post))
{
    @Html.HiddenFor(a => a.AracId)
    <div class="form-group">
        @Html.LabelFor(a => a.Marka)
        @Html.TextBoxFor(a => a.Marka, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Model)
        @Html.TextBoxFor(a => a.Model, new { @class = "form-control" })
    </div>

    <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" />
}

WebApplication4/Views/Oto/Ekle.cshtml
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Areas/Admin/Views/Shared/EkleAdmin.cshtml";
}

@using WebApplication4.Models
@model Oto

@{
    ViewBag.Title = "Arac Ekleme İşlemi";
}


<h2>Arac Ekleme</h2>




<div>

    <div class="form-group">
        @Html.LabelFor(a => a.Marka)
        @Html.TextBoxFor(a => a.Marka, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Marka)
        <label id="lblMarkaHata" style="display:none;color:red">Client Side Hata - Ad</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Model)
        @Html.TextBoxFor(a => a.Model, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Model)
        <label id="lblModelHata" style="display:none;color:red">Client Side Hata - Soyad</label>
    </div>


    <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" onclick="AracEkle()" />




</div>
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#Marka").val() == "" || $("#Model").val() == "") {
                $("#lblMarkaHata").show();
                $("#lblModelHata").show();
                hatayok = false;
            }
            return hatayok;
        }

        function AracEkle() {
            $.ajax({
                url: "/Oto/Ekle",
                method: "Post",
                data: {
                    Marka: $("#Marka").val(),
                    Model: $("#Model").val()
                },
                success: function (data) {
                    if (data == "True") {
                        alert("İşlem başarılı");
                    } else {
                        alert("Ekleme işleminde hata");
                    }
                }

            });
        }
    </script>
}

WebApplication4/Views/Oto/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_IndexAdmin.cshtml";
}

@using WebApplication4.Models.ViewModel
@model OtoViewModel


<h3>Arac Listesi</h3>


<table class="table table-striped">
    <thead>
        <tr>
            <th>AracId</th>
            <th>Marka</th>
            <th>Model</th>
            <th>İşlemler</th>
        </tr>

    </thead>
    <tbody style="">
        @foreach (var item in Model.Otomobil)
        {
            <tr>
                <td>@item.AracId</td>
                <td>@item.Marka</td>
                <td>@item.Model</td>
                <td><a href="/Oto/Duzenle/@item.AracId" class="btn btn-sm btn-primary">Düzenle</a> <a href="/Oto/Sil/@item.AracId" class="btn btn-sm btn-danger" onclick="return confirm('Bu araci silmek istediğinizden emin misiniz?')">Sil</a></td>
            </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="mdlAracEkle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Arac Ekleme</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(a => a.Ato.Marka)
                    @Html.TextBoxFor(a => a.Ato.Marka, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Ato.Marka)
                    <label id="lblMarkaHata" style="display:none;color:red">Client Side Hata - Ad</label>
                </div>
                <div class="form-group">
                    @Html.LabelFor(a => a.Ato.Model)
                    @Html.TextBoxFor(a => a.Ato.Model, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Ato.Model)
                    <label id="lblModelHata" style="display:none;color:red">Client Side Hata - Soyad</label>
                </div>


                <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" onclick="AracEkle()" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#Marka").val() == "" || $("#Model").val() == "") {
                $("#lblMarkaHata").show();
                $("#lblModelHata").show();
                hatayok = false;
            }
            return hatayok;
        }

        function AracEkle() {
            //yukardaki if else i al else aşağısı
            $.ajax({
                url: "/Oto/Ekle",
                method: "Post",
                data: {
                    Marka: $("#Marka").val(),
                    Model: $("#Model").val()
                },
                success: function (data) {
                    alert("Arac Ekleme Başarılı");
                    //console.log(data);
                    if (data == "True") {
                        alert("İşlem başarılı");
                    } else {
                        alert("Ekleme işleminde hata");
                    }
                }
                //error
            });
        }
    </script>
}

WebApplication4/Views/Oto/Listele.cshtml
@using WebApplication4.Models
@{
    ViewBag.Title = "Listele";
    Layout = "~Views/Shared/_Layout.cshtml";
}


@model IEnumerable<Oto>

<h2>Listele</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>AracId</th>
            <th>Marka</th>
            <th>Model</th>
            <th>İşlemler</th>
        </tr>

    </thead>
    <tbody style="">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.AracId</td>
                <td>@item.Marka</td>
                <td>@item.Model</td>

            </tr>
        }
    </tbody>
</table>