WebApplication4/Models/Parca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class Parca
    {
        public int ParcaId { get; set; }
        [Required]
        public string ParcaAd { get; set; }
        [Required]
        public string ParcaTur { get; set; }

    }
}

WebApplication4/Models/ViewModel/ParcaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication4.Models.ViewModel
{
    public class ParcaViewModel
    {
        public Parca Prc { get; set; }
        public IEnumerable<Parca> Parcalar { get; set; }
    }
}

WebApplication4/Controllers/ParcaController.cs
using KaraerAuto.Dal;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using WebApplication4.Models.ViewModel;

namespace WebApplication4.Controllers
{
    public class ParcaController : Controller
    {
        OtoContext ptx = new OtoContext();
        [Authorize]
        public ActionResult Index()
        {

            using (OtoContext ptx = new OtoContext())
            {
                ParcaViewModel ovm = new ParcaViewModel
                {
                    Parcalar = ptx.Parcalar.ToList()
                };

                return View(ovm);
            }

        }

        [Authorize]
        public ActionResult Ekle()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        public bool Ekle(Parca p)
        {

            if (ModelState.IsValid)
            {
                using (OtoContext ptx = new OtoContext())
                {
                    ptx.Parcalar.Add(p);
                    int sonuc = ptx.SaveChanges();
                    if (sonuc > 0)
                    {
                        return true;
                    }

                }
            }
            else
            {
                ModelState.AddModelError("ParcaId", "Bos");
            }
            return false;
        }
        public string Listele()
        {
            string liste = "";
            List<Parca> parcalistesi = ptx.Parcalar.ToList();
            foreach (var list in parcalistesi)
            {
                liste += "<br>" + list.ParcaAd + " " + list.ParcaTur + "<hr>";
            }
            return liste;
        }
        [Authorize]
        public ActionResult Duzenle(int? id)
        {
            using (OtoContext ptx = new OtoContext())
            {
                var prc = ptx.Parcalar.Find(id);

                return View(prc);
            }
        }


        [HttpPost]
        [Authorize]
        public ActionResult Duzenle(Parca prc)
        {
            using (OtoContext ptx = new OtoContext())
            {
                ptx.Entry(prc).State = EntityState.Modified;
                int sonuc = ptx.SaveChanges();
                if (sonuc > 0)
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
        }
        [Authorize]
        public ActionResult Sil(int? id)
        {
            using (OtoContext ptx = new OtoContext())
            {
                var prc = ptx.Parcalar.Find(id);
                ptx.Parcalar.Remove(prc);
                ptx.SaveChanges();
                return RedirectToAction("Index");

            }
        }
    }
}

WebApplication4/Views/Parca/Duzenle.cshtml
@model WebApplication4.Models.Parca


@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/_DuzenleAdmin.cshtml";
}

<h2>Parca Bilgileri Düzenleme İşlemi</h2>

@using (Html.BeginForm("Duzenle", "Parca", FormMethod.Post))
{
    @Html.HiddenFor(p => p.ParcaId)
    <div class="form-group">
        @Html.LabelFor(p => p.ParcaAd)
        @Html.TextBoxFor(a => a.ParcaAd, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.ParcaTur)
        @Html.TextBoxFor(p => p.ParcaTur, new { @class = "form-control" })
    </div>

    <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" />
}

WebApplication4/Views/Parca/Ekle.cshtml
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Areas/Admin/Views/Shared/EkleAdmin.cshtml";
}

@using WebApplication4.Models
@model Parca

@{
    ViewBag.Title = "Parca Ekleme İşlemi";
}


<h2>Parca Ekleme</h2>
<div>

    <div class="form-group">
        @Html.LabelFor(p => p.ParcaAd)
        @Html.TextBoxFor(p => p.ParcaAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.ParcaAd)
        <label id="lblParcaAdHata" style="display:none;color:red">Client Side Hata - Parca Ad</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.ParcaTur)
        @Html.TextBoxFor(p => p.ParcaTur, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.ParcaTur)
        <label id="lblParcaTurHata" style="display:none;color:red">Client Side Hata - Parca Tur</label>
    </div>


    <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" onclick="AracEkle()" />




</div>
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#ParcaAd").val() == "" || $("#ParcaTur").val() == "") {
                $("#lblParcaAdHata").show();
                $("#lblParcaTurHata").show();
                hatayok = false;
            }
            return hatayok;
        }

        function AracEkle() {
            $.ajax({
                url: "/Parca/Ekle",
                method: "Post",
                data: {
                    ParcaAd: $("#ParcaAd").val(),
                    ParcaTur: $("#ParcaTur").val()
                },
                success: function (data) {
                    if (data == "True") {
                        alert("İşlem başarılı-Parca Eklendi");
                    } else {
                        alert("Ekleme işleminde hata");
                    }
                }

            });
        }
    </script>
}

WebApplication4/Views/Parca/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_IndexAdmin.cshtml";
}

@using WebApplication4.Models.ViewModel
@model ParcaViewModel


<h3>Parca Listesi</h3>


<table class="table table-striped">
    <thead>
        <tr>
            <th>ParcaId</th>
            <th>Parca</th>
            <th>Tür</th>
            <th>İşlemler</th>
        </tr>

    </thead>
    <tbody style="">
        @foreach (var item in Model.Parcalar)
        {
            <tr>
                <td>@item.ParcaId</td>
                <td>@item.ParcaAd</td>
                <td>@item.ParcaTur</td>
                <td><a href="/Parca/Duzenle/@item.ParcaId" class="btn btn-sm btn-primary">Düzenle</a> <a href="/Parca/Sil/@item.ParcaId" class="btn btn-sm btn-danger" onclick="return confirm('Bu Parcayi silmek istediğinizden emin misiniz?')">Sil</a></td>
            </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="mdlAracEkle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Arac Ekleme</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(p => p.Prc.ParcaAd)
                    @Html.TextBoxFor(p => p.Prc.ParcaAd, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.Prc.ParcaAd)
                    <label id="lblParcaAdHata" style="display:none;color:red">Client Side Hata - Parca</label>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Prc.ParcaAd)
                    @Html.TextBoxFor(p => p.Prc.ParcaAd, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.Prc.ParcaAd)
                    <label id="lblParcaTurHata" style="display:none;color:red">Client Side Hata - Tur</label>
                </div>


                <input type="submit" name="btnKaydet" value="Kaydet" class="btn btn-success" onclick="AracEkle()" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        function BoslukKontrol() {
            var hatayok = true;
            if ($("#ParcaAd").val() == "" || $("#ParcaTur").val() == "") {
                $("#lblParcaAdHata").show();
                $("#lblParcaTurHata").show();
                hatayok = false;
            }
            return hatayok;
        }

        function AracEkle() {
            //yukardaki if else i al else aşağısı
            $.ajax({
                url: "/Parca/Ekle",
                method: "Post",
                data: {
                    ParcaAd: $("#ParcaAd").val(),
                    ParcaTur: $("#ParcaTur").val()
                },
                success: function (data) {
                    alert("Parca Ekleme Başarılı");
                    //console.log(data);
                    if (data == "True") {
                        alert("İşlem başarılı");
                    } else {
                        alert("Ekleme işleminde hata");
                    }
                }
                //error
            });
        }
    </script>
}

WebApplication4/Views/Parca/Listele.cshtml
@using WebApplication4.Models
@{
    ViewBag.Title = "Listele";
    Layout = "~Views/Shared/_Layout.cshtml";
}


@model IEnumerable<Parca>

<h2>Parca Listele</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ParcaId</th>
            <th>ParcaAd</th>
            <th>ParcaTur</th>
            <th>İşlemler</th>
        </tr>

    </thead>
    <tbody style="">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ParcaId</td>
                <td>@item.ParcaAd</td>
                <td>@item.ParcaTur</td>

            </tr>
        }
    </tbody>
</table>