WebApplication4/Controllers/MainController.cs
using KaraerAuto.Dal;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using WebApplication4.Models.ViewModel;

namespace WebApplication4.Controllers
{
    public class MainController : Controller
    {
        OtoContext ctx = new OtoContext();



        public ActionResult Index()
        {

            using (OtoContext ctx = new OtoContext())
            {
                OtoViewModel ovm = new OtoViewModel
                {
                    Otomobil = ctx.Otomobil.ToList()
                };

                return View(ovm);
            }

        }


        public ActionResult Ekle()
        {
            return View();
        }



        [HttpPost]

        public bool Ekle(Oto o)
        {

            if (ModelState.IsValid)
            {
                using (OtoContext ctx = new OtoContext())
                {
                    ctx.Otomobil.Add(o);
                    int sonuc = ctx.SaveChanges();
                    if (sonuc > 0)
                    {
                        return true;
                    }

                }
            }
            else
            {
                ModelState.AddModelError("AracId", "Bos");
            }
            return false;
        }

        public string Listele()
        {
            string liste = "";
            List<Oto> otolistesi = ctx.Otomobil.ToList();
            foreach (var list in otolistesi)
            {
                liste += "<br>" + list.Marka + " " + list.Model + "<hr>";
            }
            return liste;
        }
        [Authorize]
        public ActionResult Duzenle(int? id)
        {
            using (OtoContext ctx = new OtoContext())
            {
                var ato = ctx.Otomobil.Find(id);

                return View(ato);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult Duzenle(Oto ato)
        {
            using (OtoContext ctx = new OtoContext())
            {
                ctx.Entry(ato).State = EntityState.Modified;
                int sonuc = ctx.SaveChanges();
                if (sonuc > 0)
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Sil(int? id)
        {
            using (OtoContext ctx = new OtoContext())
            {
                var ato = ctx.Otomobil.Find(id);
                ctx.Otomobil.Remove(ato);
                ctx.SaveChanges();
                return RedirectToAction("Index");

            }
        }
        public string PrcListele()
        {
            string liste = "";
            List<Parca> parcalistesi = ptx.Parcalar.ToList();
            foreach (var list in parcalistesi)
            {
                liste += "<br>" + list.ParcaAd + " " + list.ParcaTur + "<hr>";
            }
            return liste;
        }
        OtoContext ptx = new OtoContext();

        public ActionResult PrcIndex()
        {

            using (OtoContext ptx = new OtoContext())
            {
                ParcaViewModel ovm = new ParcaViewModel
                {
                    Parcalar = ptx.Parcalar.ToList()
                };

                return View(ovm);
            }

        }
    }
}

WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Oto/Ekle">Arac Ekle</a></li>
                    <li><a href="/Oto/Index">Arac Listesi</a></li>
                </ul>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Karaer Tek.</p>
        </footer>
    </div>
    @RenderSection("scripts", false)
</body>
</html>

WebApplication4/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Karaer Otomotiv-Anasayfa</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/MainPage/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/MainPage/css/scrolling-nav.css" rel="stylesheet">
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/ckeditor/config.js"></script>
    <script src="~/ckeditor/styles.js"></script>
    <script src="~/ckeditor/build-config.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">Anasayfa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("Karaer Automotive", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#about">Hakkımızda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#services">Ürünler</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Bize Ulaş!</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="bg-primary text-white">
        <div class="container text-center">
            <h1>Karaer Otomotiv</h1>
            <p class="lead">Karaer Otomotiv.Sizin Bir Parçanız...</p>
        </div>
    </header>

    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Hakkımızda</h2>
                    <p class="lead">Karaer Otomotiv 2019 yılında faaliyetlerine başlamış bir Otomotiv Şirketidir.Karaer Şirketler Grubunun bir parçası olarak Türkiye ve Dünyada 23 ülkede şubesiyle güvenilir ve kaliteli hizmet vermekteyiz</p>
                    <ul>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="bg-light">
        <div class="container">

            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Hizmet Verdiğimiz Araçlar</h2>
                    <p class="lead">Hizmet verdiğimiz araçlar ve ürünler listesi sayesinde hangi parça ve araçlar stokta var hemen görüntüleyin!</p>
                    <div class="container body-content">
                        @RenderBody()
                        <hr />

                    </div>
                    @RenderSection("scripts", false)
                </div>
                <a href="/Main/PrcIndex" class="btn btn-primary btn-lg active " role="button" aria-pressed="true">Ürünler'e Gitmek İçin Tıklayınız..</a>

            </div>
        </div>

    </section>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Bize Ulaşın </h2>
                    <p class="lead">İstek,öneri ve şikayetleriniz için lütfen bize yazın.</p>
                    @Html.TextArea("editor1")
                    <input type="button" value="Click me" onclick="">
                    <script type="text/javascript">
                     var editor = CKEDITOR.instances['editor1'];
                     if (editor) { editor.destroy(true); }
                    CKEDITOR.replace('editor1', {
                    enterMode: CKEDITOR.ENTER_BR,

                             });
                     CKFinder.setupCKEditor(null, '@Url.Content("~/ckeditor/ckfinder/")');
                    </script>

                    <a href="#" class="btn btn-primary btn-lg active b" role="button" aria-pressed="true">Gönder..</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Karaer Tek Gmbh 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/MainPage/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/MainPage/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/Content/MainPage/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="~/Content/MainPage/js/scrolling-nav.js"></script>


</body>

</html>

WebApplication4/Views/Shared/_LayoutParc.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Karaer Otomotiv-Anasayfa</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/MainPage/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/MainPage/css/scrolling-nav.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/Main/Index">Anasayfa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                </ul>
            </div>
        </div>
    </nav>

    <header class="bg-primary text-white">
        <div class="container text-center">
            <h1>Karaer Otomotiv</h1>
            <p class="lead">Karaer Otomotiv.Sizin Bir Parçanız...</p>
        </div>
    </header>



    <section id="services" class="bg-light">
        <div class="container">

            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Hizmet Verdiğimiz Araçlar</h2>
                    <p class="lead">Hizmet verdiğimiz araçlar ve ürünler listesi sayesinde hangi parça ve araçlar stokta var hemen görüntüleyin!</p>
                    <div class="container body-content">
                        @RenderBody()
                        <hr />

                    </div>
                    @RenderSection("scripts", false)
                </div>


            </div>
        </div>

    </section>


    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Karaer Tek Gmbh 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/MainPage/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/MainPage/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/Content/MainPage/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="~/Content/MainPage/js/scrolling-nav.js"></script>

</body>

</html>